your_Blog/Controllers/Article/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using your_Blog.Models;

namespace your_Blog.Controllers.Article
{
    public class ArticleController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();

        // GET: Article
        public async Task<ActionResult> Index(int page = 1)
        {
            int pageSize = 3;
            ViewBag.Category = db.Categories.ToList().Where(c => c.Id != 1);
            ViewBag.Tag = db.Tags.ToList();

            IEnumerable<ArticleModel> articles = await db.Articles
                .Include(a => a.Category)
                .OrderByDescending(a => a.Id)
                .Skip((page - 1) * pageSize)
                .Take(pageSize).ToListAsync();

            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = db.Articles.Count() };

            IndexViewModel<ArticleModel> ivm = new IndexViewModel<ArticleModel>() { Articles = articles, pageInfo = pageInfo };

            return View(ivm);
        }


        // GET: Article/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArticleModel articleModel = await db.Articles.FindAsync(id);


            if (articleModel == null)
            {
                return HttpNotFound();
            }
            return View(articleModel);
        }

        // GET: Article/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories.ToList().Where(c => c.Id != 1).ToList(), "Id", "Name");
            ViewBag.Tags = db.Tags.ToList();

            return View();
        }

        // POST: Article/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(
            [Bind(Include = "Id,Name,ShortDescription,Description,CategoryId")] ArticleModel articleModel,
            int[] selectedTags,
            HttpPostedFileBase uploadFoto)
        {
            if (ModelState.IsValid)
            {
                articleModel.Date = DateTime.Now;
                if (selectedTags != null)
                {
                    //получаем выбранные теги
                    foreach (var c in db.Tags.Where(co => selectedTags.Contains(co.Id)))
                    {
                        articleModel.Tags.Add(c);
                    }
                }

                if (uploadFoto != null)
                {
                    byte[] fotoData = null;
                    using (var binaryReader = new BinaryReader(uploadFoto.InputStream))
                    {
                        fotoData = binaryReader.ReadBytes(uploadFoto.ContentLength);
                    }
                    articleModel.HeroImage = fotoData;
                }

                db.Articles.Add(articleModel);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories.ToList().Where(c => c.Id != 1).ToList(), "Id", "Name");

            return View(articleModel);
        }

        // GET: Article/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArticleModel articleModel = await db.Articles.FindAsync(id);

            if (articleModel == null)
            {
                return HttpNotFound();
            }

            ViewBag.Tags = db.Tags.Include(x => x.Articles).ToList();
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", articleModel.CategoryId);

            return View(articleModel);
        }

        // POST: Article/Edit

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(
            ArticleModel articleModel,
            int[] selectedTags,
            HttpPostedFileBase uploadFoto)
        {
            ArticleModel newAtricle = db.Articles.Find(articleModel.Id);
            newAtricle.Name = articleModel.Name;
            newAtricle.ShortDescription = articleModel.ShortDescription;
            newAtricle.CategoryId = articleModel.CategoryId;
            newAtricle.Description = articleModel.Description;
            newAtricle.Date = DateTime.Now;
            newAtricle.HeroImage = articleModel.HeroImage;

            if (ModelState.IsValid)
            {

                if (selectedTags != null)
                {
                    newAtricle.Tags.Clear();
                    //получаем выбранные теги
                    foreach (var c in db.Tags.Where(co => selectedTags.Contains(co.Id)))
                    {
                        newAtricle.Tags.Add(c);
                    }
                }

                if (uploadFoto != null)
                {
                    byte[] fotoData = null;
                    using (var binaryReader = new BinaryReader(uploadFoto.InputStream))
                    {
                        fotoData = binaryReader.ReadBytes(uploadFoto.ContentLength);
                    }
                    newAtricle.HeroImage = fotoData;
                }

                db.Entry(newAtricle).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", articleModel.CategoryId);

            return View(articleModel);
        }

        // GET: Article/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArticleModel articleModel = await db.Articles.FindAsync(id);

            if (articleModel == null)
            {
                return HttpNotFound();
            }

            return View(articleModel);
        }

        // POST: Article/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            ArticleModel articleModel = await db.Articles.FindAsync(id);
            db.Articles.Remove(articleModel);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        /// <summary>
        /// Фильтрация статей по категориям.
        /// </summary>
        /// <param name="name">Выбранная категория.</param>
        /// <param name="page">Страница.</param>
        /// <returns>Статьи.</returns>
        public ActionResult Category(string name, int page = 1)
        {
            CategoryModel category = db.Categories.Include(p => p.Articles).FirstOrDefault(t => t.Name == name.ToString());
            if (category == null)
            {
                return RedirectToAction("Index");
            }

            int pageSize = 3;

            IEnumerable<ArticleModel> articles = category.Articles.OrderByDescending(a => a.Id).Skip((page - 1) * pageSize).Take(pageSize).ToList();
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = category.Articles.Count() };
            IndexViewModel<ArticleModel> ivm = new IndexViewModel<ArticleModel>() { Articles = articles, pageInfo = pageInfo };

            ViewBag.Title = name;

            ViewBag.Category = db.Categories.ToList().Where(c => c.Id != 1);
            ViewBag.Tag = db.Tags.ToList();

            return View("Index", ivm);
        }

        /// <summary>
        /// Фильтрация статей по тегам.
        /// </summary>
        /// <param name="selectedTags">Выбранные теги.</param>
        /// <param name="page">Страница.</param>
        /// <returns>Статьи.</returns>
        public ActionResult Tag(int[] selectedTags, int page = 1)
        {
            IEnumerable<ArticleModel> articles = default;
            int pageSize = 3;

            PageInfo pageInfo;

            if (selectedTags == null)
            {
                return RedirectToAction("Index");
            }

            if (selectedTags != null && selectedTags.Count() != 1)
            {
                IEnumerable<TagModel> tags = db.Tags.Include(p => p.Articles).Where(co => selectedTags.Contains(co.Id));
                if (tags == null)
                {
                    return RedirectToAction("Index");
                }

                IEnumerable<ArticleModel> articlesbuffer = default;

                foreach (var item in tags)
                {
                    articlesbuffer = item.Articles.OrderByDescending(a => a.Id).Skip((page - 1) * pageSize).Take(pageSize).ToList();
                    articles = articlesbuffer.Union(item.Articles.OrderBy(a => a.Id).Skip((page - 1) * pageSize).Take(pageSize).ToList());
                }
                pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = articles.Count() };
            }
            else
            {
                var tagName = selectedTags[0].ToString();
                TagModel tag = db.Tags.Include(p => p.Articles).FirstOrDefault(t => t.Id.ToString() == tagName);
                articles = tag.Articles.OrderByDescending(a => a.Id).Skip((page - 1) * pageSize).Take(pageSize).ToList();
                pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = tag.Articles.Count() };
            }

your_Blog/Controllers/Article/CategoryController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using your_Blog.Models;

namespace your_Blog.Controllers.Article
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();

        // GET: Category
        public ActionResult Index()
        {
            return View(db.Categories.ToList().Where(c => c.Id != 1));
        }

        // GET: Category/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null || id == 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            CategoryModel categoryModel = db.Categories.Find(id);

            if (categoryModel == null)
            {
                return HttpNotFound();
            }
            return View(categoryModel);
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] CategoryModel categoryModel)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(categoryModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categoryModel);
        }

        // GET: Category/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null || id == 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            CategoryModel categoryModel = db.Categories.Find(id);

            if (categoryModel == null)
            {
                return HttpNotFound();
            }
            return View(categoryModel);
        }

        // POST: Category/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] CategoryModel categoryModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categoryModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categoryModel);
        }

        // GET: Category/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null || id == 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoryModel categoryModel = db.Categories.Find(id);
            if (categoryModel == null)
            {
                return HttpNotFound();
            }
            return View(categoryModel);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CategoryModel categoryModel = db.Categories.Find(id);
            var article = db.Articles.Where(p => p.CategoryId == id).ToList();

            foreach (var item in article)
            {
                ArticleModel articleModel = db.Articles.Find(item.Id);
                articleModel.CategoryId = 1;
                db.Entry(articleModel).State = EntityState.Modified;
                db.SaveChanges();
            }

            db.Categories.Remove(categoryModel);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

your_Blog/Controllers/Article/TagController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using your_Blog.Models;

namespace your_Blog.Controllers.Article
{
    [Authorize]
    public class TagController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();

        // GET: TagModels
        public ActionResult Index()
        {
            return View(db.Tags.ToList());
        }

        // GET: TagModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            TagModel tagModel = db.Tags.Find(id);

            if (tagModel == null)
            {
                return HttpNotFound();
            }

            return View(tagModel);
        }

        // GET: TagModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TagModels/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] TagModel tagModel)
        {
            if (ModelState.IsValid)
            {
                db.Tags.Add(tagModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tagModel);
        }

        // GET: TagModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TagModel tagModel = db.Tags.Find(id);
            if (tagModel == null)
            {
                return HttpNotFound();
            }
            return View(tagModel);
        }

        // POST: TagModels/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] TagModel tagModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tagModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tagModel);
        }

        // GET: TagModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TagModel tagModel = db.Tags.Find(id);
            if (tagModel == null)
            {
                return HttpNotFound();
            }
            return View(tagModel);
        }

        // POST: TagModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TagModel tagModel = db.Tags.Find(id);
            db.Tags.Remove(tagModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

your_Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel='stylesheet' id='reset-css' href='~/Content/css/reset.css' type='text/css' media='all' />
    <link rel='stylesheet' id='superfish-css' href='~/Content/css/superfish.css' type='text/css' media='all' />
    <link rel='stylesheet' id='fontawsome-css' href='~/Content/css/font-awsome/css/font-awesome.css' type='text/css' media='all' />
    <link rel='stylesheet' id='orbit-css-css' href='~/Content/css/orbit.css' type='text/css' media='all' />
    <link rel='stylesheet' id='style-css' href='~/Content/css/style.css' type='text/css' media='all' />
    <link rel='stylesheet' id='color-scheme-css' href='~/Content/css/color/green.css' type='text/css' media='all' />
    <link rel="stylesheet" href="~/Content/css/zerogrid.css" type="text/css" media="screen">
    <link rel="stylesheet" href="~/Content/css/responsive.css" type="text/css" media="screen">
    <link rel="stylesheet" href="~/Content/daterangepicker.css">
    <link rel="stylesheet" href="~/Content/Site.css" type="text/css" media="screen">
    <script type='text/javascript' src='~/Scripts/js/jquery.js'></script>
    <script type='text/javascript' src='~/Scripts/js/jquery-migrate.min.js'></script>
    <script type='text/javascript' src='~/Scripts/js/jquery-1.10.2.min.js'></script>
    <script type='text/javascript' src='~/Scripts/js/jquery.carouFredSel-6.2.1-packed.js'></script>
    <script type='text/javascript' src='~/Scripts/js/hoverIntent.js'></script>
    <script type='text/javascript' src='~/Scripts/js/superfish.js'></script>
    <script type='text/javascript' src='~/Scripts/js/orbit.min.js'></script>
    <script type='text/javascript' src='~/Scripts/moment.min.js'></script>
    <script type='text/javascript' src='~/Scripts/daterangepicker.js'></script>
    <script type='text/javascript' src='~/Scripts/syte.js'></script>
    <script src="~/Scripts/js/css3-mediaqueries.js"></script>
</head>
<body class="home blog">
    <!-- Start Header -->
    <div class="container zerogrid">
        <div class="col-full">
            <div class="wrap-col">
                <div id="header-nav-container">


                    <!-- Navigation Menu -->

                    <ul class="sf-menu headerMenuItemWrp">
                        <div class="headerMenuItemLeft">
                            <li>
                                @Html.ActionLink("Статьи", "Index", "Article", new { area = "" }, new { @class = "menu-item current-menu-item" })
                            </li>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="menu-item">
                                    <a href="#">
                                        Админ. панель
                                    </a>
                                    <ul class="sub-menu">
                                        <li class="menu-item">
                                            @Html.ActionLink("Теги", "Index", "Tag")
                                        </li>
                                        <li class="menu-item">
                                            @Html.ActionLink("Категории", "Index", "Category")
                                        </li>
                                    </ul>
                                </li>
                            }
                        </div>
                        <div class="headerMenuItemRight">
                            @Html.Partial("_LoginPartial")
                        </div>
                    </ul>
                    <!-- End Navigation Menu -->
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>

    <div class="container zerogrid">

        <!-- Start Posts Container -->
        <div class="col-2-3" id="post-container">
            <div class="wrap-col">

                <!-- Start Post Item -->
                @RenderBody()
                <!-- End Post Item -->

                <div class="clear"></div>
            </div>
        </div>
        <!-- End Posts Container -->

        <div class="clear"></div>
    </div>
    <!-- End Main Container -->
    <!-- Start Footer -->
    <div class="spacing-30"></div>
    <div class="container zerogrid">
        <div id="footer-container" class="col-full">
            <div class="wrap-col">
                <!-- Footer Copyright -->
                <p>Your-Blog &copy; 2019 </p>
                <!-- End Footer Copyright -->
                <div class="clear"></div>
            </div>
        </div>
    </div>
    <!-- End Footer -->

</body>

</html>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

your_Blog/Views/Shared/_LayoutIndex.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel='stylesheet' id='reset-css' href='~/Content/css/reset.css' type='text/css' media='all' />
    <link rel='stylesheet' id='superfish-css' href='~/Content/css/superfish.css' type='text/css' media='all' />
    <link rel='stylesheet' id='fontawsome-css' href='~/Content/css/font-awsome/css/font-awesome.css' type='text/css' media='all' />
    <link rel='stylesheet' id='orbit-css-css' href='~/Content/css/orbit.css' type='text/css' media='all' />
    <link rel='stylesheet' id='style-css' href='~/Content/css/style.css' type='text/css' media='all' />
    <link rel='stylesheet' id='color-scheme-css' href='~/Content/css/color/green.css' type='text/css' media='all' />
    <link rel="stylesheet" href="~/Content/css/zerogrid.css" type="text/css" media="screen">
    <link rel="stylesheet" href="~/Content/css/responsive.css" type="text/css" media="screen">
    <link rel="stylesheet" href="~/Content/Site.css" type="text/css" media="screen">
    <script type='text/javascript' src='~/Scripts/js/jquery.js'></script>
    <script type='text/javascript' src='~/Scripts/js/jquery-migrate.min.js'></script>
    <script type='text/javascript' src='~/Scripts/js/jquery-1.10.2.min.js'></script>
    <script type='text/javascript' src='~/Scripts/js/jquery.carouFredSel-6.2.1-packed.js'></script>
    <script type='text/javascript' src='~/Scripts/js/hoverIntent.js'></script>
    <script type='text/javascript' src='~/Scripts/js/superfish.js'></script>
    <script type='text/javascript' src='~/Scripts/js/orbit.min.js'></script>
    <script src="~/Scripts/js/css3-mediaqueries.js"></script>
</head>
<body class="home blog">
    <!-- Start Header -->
    <div class="container zerogrid">
        <div class="col-full">
            <div class="wrap-col">
                <div id="header-nav-container">

                    <!-- Navigation Menu -->

                    <ul class="sf-menu headerMenuItemWrp">
                        <div class="headerMenuItemLeft">
                            <li>
                                @Html.ActionLink("Статьи", "Index", "Article", new { area = "" }, new { @class = "menu-item current-menu-item" })
                            </li>
                            @if (User.Identity.IsAuthenticated)
                            {
                        <li class="menu-item">
                            <a href="#">
                                Админ. панель
                            </a>
                            <ul class="sub-menu">
                                <li class="menu-item">
                                    @Html.ActionLink("Теги", "Index", "Tag")
                                </li>
                                <li class="menu-item">
                                    @Html.ActionLink("Категории", "Index", "Category")
                                </li>
                            </ul>
                        </li>
                            }
                            
                        </div>
                        <div class="headerMenuItemRight">
                            @Html.Partial("_LoginPartial")
                        </div>
                    </ul>
                    <!-- End Navigation Menu -->
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>

    <div class="container zerogrid">

        <!-- Start Posts Container -->
        <div class="col-2-3" id="post-container">
            <div class="wrap-col">

                <!-- Start Post Item -->
                @RenderBody()
                <!-- End Post Item -->

                <div class="clear"></div>
            </div>
        </div>
        <!-- End Posts Container -->
        <!-- Start Sidebar -->
        <div class="col-1-3">
            <div class="wrap-col">

                <div class="widget-container">
                    @Html.Partial("CategoryPartial")
                </div>

                <div class="widget-container">
                    @Html.Partial("TagsPartial")
                    <!-- End Widget -->
                    <div class="clear"></div>
                </div>
                <div class="widget-container">
                    @Html.Partial("DatePartial")
                </div>
                <div class="clear"></div>
            </div>
        </div>        <!-- End Sidebar -->

        <div class="clear"></div>
    </div>
    <!-- End Main Container -->
    <!-- Start Footer -->
    <div class="spacing-30"></div>
    <div class="container zerogrid">
        <div id="footer-container" class="col-full">
            <div class="wrap-col">
                <!-- Footer Copyright -->
                <p>Your-Blog &copy; 2019 </p>
                <!-- End Footer Copyright -->

                <div class="clear"></div>
            </div>
        </div>
    </div>
    <!-- End Footer -->

</body>

</html>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)

</body>
</html>